edit acenfat.lib
edit acenhrk.lib
edit acenta.lib
edit AJANDA.LIB
edit aksiyhrk.lib
edit aksiyon.lib
edit banka.lib
edit bilbord.lib
edit cast.lib
edit cektr.lib
edit cevap1.lib
edit cevap2.lib
edit dagilim.lib
edit depkod.lib
edit detist.lib
edit dov-boz.lib
edit doviz.lib
edit exthrk.lib
edit extpost.lib
edit fatura.lib
edit fihrist.lib
edit fiyat.lib
edit kimlik.lib
edit genel.lib
edit genelfis.lib
edit halk.lib
edit harf.lib
edit istdata.lib
edit ISYERI.LIB
edit kart.lib
edit kat.lib
edit KLLNC.LIB
edit kodlar02.lib
edit kontrat.lib
edit konuk.lib
edit konum.lib
edit kur.lib
edit mail.lib
edit odadegis.lib
edit odalar.lib
edit odenmez.lib
edit onavans.lib
edit onkasa.lib
edit ozluk.lib
edit postkod.lib
edit PROSIF.LIB
edit rez.lib
edit romhrk.lib
edit silhrk.lib
edit soru.lib
edit takvim.lib
edit teknik.lib
edit teldata.lib
edit telkod.lib
edit turizm.lib
edit ulke.lib
edit uzatma.lib
edit fiyatana.lib
edit kategori.lib
edit depozit.lib
edit LISTE.LIB
edit dokumer.lib
edit MENUTEXT.LIB
edit rapordzg.lib
edit telkim.lib
edit telerr.lib
edit xrez.lib
edit rapor.lib
edit xkonuk.lib
edit errorlog.lib
edit xozluk.lib
edit HELPMENU.LIB
edit prtler.lib
edit hkonuk.lib
